
package br.univali.rbcprinter.visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class TelaPrincipal extends javax.swing.JFrame {
    private List<Integer> tuplaNomes = new ArrayList();
    
    public TelaPrincipal() {
        initComponents();
        this.setTitle("RBC Printers");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        configuraComboBox();
        
        botaoBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new TelaTabela(getSelectedItemsIndex()).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelCadastroCaso = new javax.swing.JLabel();
        boxTipoImpressora = new javax.swing.JComboBox();
        labelTipo = new javax.swing.JLabel();
        labelConector = new javax.swing.JLabel();
        boxConector = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        boxFonte = new javax.swing.JComboBox();
        labelLEDPower = new javax.swing.JLabel();
        boxLEDPower = new javax.swing.JComboBox();
        boxLEDProcessamento = new javax.swing.JComboBox();
        labelLEDProcessamento = new javax.swing.JLabel();
        botaoBuscar = new javax.swing.JToggleButton();
        labelIluminador = new javax.swing.JLabel();
        boxIluminador = new javax.swing.JComboBox();
        boxImprimindo = new javax.swing.JComboBox();
        labelImprimindo = new javax.swing.JLabel();
        boxEscaneado = new javax.swing.JComboBox();
        labelEscaneando = new javax.swing.JLabel();
        boxAlimentador = new javax.swing.JComboBox();
        labelAlientador = new javax.swing.JLabel();
        boxEstufa = new javax.swing.JComboBox();
        labelEstufa = new javax.swing.JLabel();
        boxTonner = new javax.swing.JComboBox();
        labelTonner = new javax.swing.JLabel();
        labelLEDEthernet = new javax.swing.JLabel();
        boxLEDEthernet = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelPrincipal.setAutoscrolls(true);

        labelCadastroCaso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCadastroCaso.setText("Buscar solução");

        labelTipo.setText("Tipo da impressora:");

        labelConector.setText("O conector é:");

        jLabel1.setText("Impressora esta ligada a uma fonte?:");

        labelLEDPower.setText("LED Power está:");

        labelLEDProcessamento.setText("LED Processamento está:");

        botaoBuscar.setText("Buscar");

        labelIluminador.setText("Iluminador do scanner:");

        labelImprimindo.setText("Esta imprimindo?:");

        labelEscaneando.setText("Esta escaneando?:");

        labelAlientador.setText("Alimentador esta:");

        labelEstufa.setText("É utilizado estufa?:");

        labelTonner.setText("O tonner esta:");

        labelLEDEthernet.setText("LED Ethernet está:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastroCaso)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(boxConector, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boxTipoImpressora, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(labelConector)
                                        .addComponent(jLabel1)
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(boxLEDPower, javax.swing.GroupLayout.Alignment.LEADING, 0, 95, Short.MAX_VALUE)
                                            .addComponent(boxFonte, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(labelLEDPower))
                                    .addGap(83, 83, 83))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(boxLEDEthernet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelLEDEthernet))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTonner)
                                .addComponent(boxTonner, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAlientador)
                                .addComponent(boxAlimentador, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelImprimindo)
                                .addComponent(boxImprimindo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelEscaneando)
                                .addComponent(boxEscaneado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelEstufa)
                                .addComponent(boxEstufa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelLEDProcessamento)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                        .addComponent(boxLEDProcessamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelIluminador)
                                        .addComponent(boxIluminador, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoBuscar))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroCaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxTipoImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelImprimindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxImprimindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelConector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxConector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelEscaneando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxEscaneado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelAlientador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxAlimentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelLEDPower)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxLEDPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelEstufa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxEstufa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTonner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxTonner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(botaoBuscar))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelLEDEthernet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxLEDEthernet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLEDProcessamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxLEDProcessamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIluminador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxIluminador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public List<Integer> getSelectedItemsIndex() {
        List<Integer> tupla = new ArrayList();
        tupla.add(boxTipoImpressora.getSelectedIndex());
        tupla.add(boxConector.getSelectedIndex());
        tupla.add(boxFonte.getSelectedIndex());
        tupla.add(boxLEDPower.getSelectedIndex());
        tupla.add(boxLEDEthernet.getSelectedIndex());
        tupla.add(boxLEDProcessamento.getSelectedIndex());
        tupla.add(boxIluminador.getSelectedIndex());
        tupla.add(boxImprimindo.getSelectedIndex());
        tupla.add(boxEscaneado.getSelectedIndex());
        tupla.add(boxAlimentador.getSelectedIndex());
        tupla.add(boxEstufa.getSelectedIndex());
        tupla.add(boxTonner.getSelectedIndex());
        return tupla;
    }
    
    public void configuraComboBox() {
        //  Tipo
        boxTipoImpressora.addItem("Matricial");
        boxTipoImpressora.addItem("Jato de tinta");
        //  Cabeamento
        boxConector.addItem("USB");
        boxConector.addItem("Paralelo");
        boxConector.addItem("Ethernet");
        //  Fonte
        boxFonte.addItem("Sim");
        boxFonte.addItem("Não");
        //  LED Power
        boxLEDPower.addItem("Ligado");
        boxLEDPower.addItem("Desligado");
        boxLEDPower.addItem("Piscando");
        //  LED Ethernet
        boxLEDEthernet.addItem("Ligado");
        boxLEDEthernet.addItem("Desligado");
        boxLEDEthernet.addItem("Piscando");        
        //  LED Processamento
        boxLEDProcessamento.addItem("Ligado");
        boxLEDProcessamento.addItem("Desligado");
        boxLEDProcessamento.addItem("Piscando");
        //  Iluminador Scanner
        boxIluminador.addItem("Aceso");
        boxIluminador.addItem("Apagado");
        boxIluminador.addItem("Não possui");
        //  Esta imprimindo
        boxImprimindo.addItem("Sim");
        boxImprimindo.addItem("Não");
        boxImprimindo.addItem("Impressão falhada");
        boxImprimindo.addItem("Imprime em branco");
        //  Esta escaneando
        boxEscaneado.addItem("Sim");
        boxEscaneado.addItem("Não");
        //  Alimentador
        boxAlimentador.addItem("Cheio");
        boxAlimentador.addItem("Poucas folhas");
        boxAlimentador.addItem("Vazio");
        //  Estufa
        boxEstufa.addItem("Sim");
        boxEstufa.addItem("Não");
        //  Tonner
        boxTonner.addItem("Cheio");
        boxTonner.addItem("Pouca carga");
        boxTonner.addItem("Não há tonner");
    }
    
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoBuscar;
    private javax.swing.JComboBox boxAlimentador;
    private javax.swing.JComboBox boxConector;
    private javax.swing.JComboBox boxEscaneado;
    private javax.swing.JComboBox boxEstufa;
    private javax.swing.JComboBox boxFonte;
    private javax.swing.JComboBox boxIluminador;
    private javax.swing.JComboBox boxImprimindo;
    private javax.swing.JComboBox boxLEDEthernet;
    private javax.swing.JComboBox boxLEDPower;
    private javax.swing.JComboBox boxLEDProcessamento;
    private javax.swing.JComboBox boxTipoImpressora;
    private javax.swing.JComboBox boxTonner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAlientador;
    private javax.swing.JLabel labelCadastroCaso;
    private javax.swing.JLabel labelConector;
    private javax.swing.JLabel labelEscaneando;
    private javax.swing.JLabel labelEstufa;
    private javax.swing.JLabel labelIluminador;
    private javax.swing.JLabel labelImprimindo;
    private javax.swing.JLabel labelLEDEthernet;
    private javax.swing.JLabel labelLEDPower;
    private javax.swing.JLabel labelLEDProcessamento;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTonner;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
