package br.univali.egjide.visao;

import br.univali.egjide.modelo.Simbolo;
import br.univali.egjide.gals.Semantico;
import javax.swing.table.DefaultTableModel;

public class TelaTabela extends javax.swing.JFrame {

    public TelaTabela(EgjIDE aThis) {
        initComponents();
        this.setVisible(true);
        this.setTitle("Tabela de simbolos");
        this.setResizable(false);
        this.setLocationRelativeTo(aThis);
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("nome");    //  0
        modelo.addColumn("tipo");    //  1
        modelo.addColumn("inic.");   //  2
        modelo.addColumn("usado");   //  3
        modelo.addColumn("escopo");  //  4
        modelo.addColumn("param.");  //  5
        modelo.addColumn("pos");     //  6
        modelo.addColumn("vetor");   //  7        
        modelo.addColumn("funcao");  //  8
        
        String[] vet = new String[9];
        for (Simbolo s : Semantico.tabela) { 
            vet[0] = s.getNome();
            vet[1] = s.getTipo();
            vet[2] = String.valueOf(s.isInicializado());
            vet[3] = String.valueOf(s.isUsada());
            vet[4] = s.getEscopo();
            vet[5] = String.valueOf(s.isParam());
            vet[6] = String.valueOf(s.getPos());
            vet[7] = String.valueOf(s.isVet());            
            vet[8] = String.valueOf(s.isFunc());
            
            modelo.addRow(vet);
        }
        
        tableSemantica.setModel(modelo);
        tableSemantica.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSemantica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableSemantica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableSemantica);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSemantica;
    // End of variables declaration//GEN-END:variables
}
